image: node:latest

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm install
    - echo "Installing is done!"
  artifacts:
    paths:
      - node_modules/
    expire_in: 30min

lint-job:
  stage: test
  script:
    - npm run lint
    - echo "Linting code running... ."

prettier-job:
  stage: test
  script:
    - npm run prettier
    - echo "Prettier code running... ."

build:
  stage: build
  script:
    - npm run build
    - echo "Building site"
  artifacts:
    paths:
      - build/
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"
