image: node:latest

stages:         
  - install
  - test

install:   
  stage: install
  script:
    - echo "Installing is done!"

lint-job:   
  stage: test    
  script:
    - npm run lint
    - echo "Linting code running... ."

prettier-job:   
  stage: test    
  script:
    - npm run prettier
    - echo "Prettier code running... ."

build:          
  stage: build
  script:
    - npm run build
    - echo "Building site"
  artifacts:
    paths:
      - out/
  rules:
      - if: "$CI_COMMIT_BRANCH == 'main'"
